### ISSUE TITLE
Mock Up Template para Cartelería Digital. FECHA: 29/02

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Bayer#1]
@FAAREIA en la misma línea que te pedí los templates para Digital Signage de Benteveo, te pido más prioritario todavía un mock up en photoshop para el lunes para Bayer.

La diagramación seguí la misma que en esta captura que te adjunto...

![mock-up-nueva-estetica-fotos](https://cloud.githubusercontent.com/assets/6719872/13332852/bf775730-dbe2-11e5-86e2-b2ad41ac56f1.png)

pero con la estética de este manual de marca:

[CINCO CORPORATIVO 2[1].pdf](https://github.com/LeandroBraier/Bayer/files/147216/CINCO.CORPORATIVO.2.1.pdf)
[APLICACION DE MARCA CINCO[1].pdf](https://github.com/LeandroBraier/Bayer/files/147217/APLICACION.DE.MARCA.CINCO.1.pdf)
https://www.wetransfer.com/downloads/086c7ab1b81590915e5cdfebdbadf6e220160225201214/35cde7

Es un canal de cartelería digital interno. Solo tenés que cambiarle la estética a la que te paso y agregar el logo de CINCO al estilo de un canal de TV (arriba a la izquierda)

Cualquier duda avisame pero confirmame si recibiste porfa y si llegan para el lunes.

abrazo

**Comment by FAAREIA** [comment]
Ahi va el panel. El manuel de marca solo posee el logo por lo que no había decisiones estéticas a seguir. Me base principalmente en generar un panel con toda la data disponible.

![cinco](https://cloud.githubusercontent.com/assets/6184969/13394392/d40dbc34-dec6-11e5-88eb-da4a5c4ee8d1.png)

**Comment by LeandroBraier** [comment]
Gracias @FAAREIA ! Quedó muy muy linda! Muy buen uso del espacio, el color y la tipografía.

Te paso feedback para ya modificarlo y mandarlo al cliente.

1) Falta el estado del tránsito. Yo lo ubicaría debajo de los rss de noticias.

2) Lo de las fotos lo incluiste porque sabés si los RSS pueden traer fotos? Tengo entendido que no. En ese caso reemplazá las fotos por el logo de cada diario y listo. Eso te va a dejar más espacio para el tránsito también, que podría tener un logo propio (un camioncito o algo por el estilo)

3) La cartelería digital no es clickeable, así que habría que quitar  lo de "IR A LA INTRANET". En ese espacio podría ir el nombre de la categoría en lugar de abajo. Lo digo porque cuando pongamos videos la parte de abajo de la imagen va a estar tomada por los subtítulos, así que va a haber que incluirlo arriba. 

4) Te pido una segunda versión con como quedaría un ejemplo con video, que va a ser usado el 70% del tiempo que dure cada loop de contenido.

abrazo

**Comment by FAAREIA** [comment]
Creo que si puede traer imágenes el rss pero si hay estado de tránsito no va a entrar la foto.
El estado de tránsito tiene que ser algo asi? http://www.ambito.com/servicios/transito/
Son muchos datos los que podemos poner, no sería mejor hacer una pantalla a parte para eso?

**Comment by LeandroBraier** [comment]
El estado del tránsito es un rss creado en base al Twitter de Jota Leonetti:

https://twitrss.me/twitter_user_to_rss/?user=jotaleonetti

Es un RSS más. Averiguate bien lo del RSS. En los nuestros creo que toma
foto.

abrazo

2016-02-29 10:16 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Al video le pongo los controles?
Digo porque si no es táctil el usuario final vería una foto sin bajada nomás.

**Comment by LeandroBraier** [comment]
Fede, es una pantalla en una cafetería, no una página web. No te olvides de
eso. No se puede hacer clic ni interactividad alguna. Es un video nada más,
solo que en lugar de ocupar toda la pantalla, ocupa una porción y tiene
todo lo demás alrededor. Tampoco va embebido, es un video metido adentro,
sin controles ni titulo ni nada. Solo debería tener el nombre de la
categoría de video. Para este ejemlo podés usar "MUNDO VIRAL"

abrazo

**Comment by FAAREIA** [comment]
Ahi va.
A novedades le saqué la foto y el nombre del diario, lo cual me parece que no suma como dato si solo se van a leer títulos rápidamente.

![foto](https://cloud.githubusercontent.com/assets/6184969/13397062/e94bdeae-ded6-11e5-947c-c7895964ace2.png)
![video](https://cloud.githubusercontent.com/assets/6184969/13397063/e967ccae-ded6-11e5-903b-1c097e29424e.png)

**Comment by LeandroBraier** [comment]
Me gusta mucho Fede. La verdad que estéticamente genial.

1) El problema del template del video es que el formato de imagen no es de
video, es decir, 16:9. Necesito ver como quedaría un video en ese contexto.

2) La propuesta que hacés para novedades debería decir NOTICIAS, no
novedades, y la verdad no me termina de cerrar. No hace falta tanta info de
tránsito y creo que dificulta mucho la lectura dispuesto así el texto.
Prefiero que tránsito sea un diario más y probemos una versión con nombre
de diario y otra sin, me parece que los nombres son necesarios porque a
veces la noticia que muestran es la misma pero con distinto enfoque. No
podemos controlar lo que cada uno saca en su RSS.

2016-02-29 11:24 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Si pongo el video 16:9 no podría haber ningun otro dato encima, excepto que tape parte del video con algo de transparencia. 16:9 es exactament 1920x1080
Lo otro ahi lo pruebo

**Comment by LeandroBraier** [comment]
No hay problema con que no haya otro dato sobre el video. Si podría haberlo
arriba de todo, donde ponés el nombre de la categoría. Los videos los
editamos nosotros y además la plataforma de cartelería digital permite
encima cosas por sobre el video también.

abrazo y gracias

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-02-29 11:30 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Ahi va la foto con noticias y tránsito.
El video lo simplifiqué y le puse la data básica

![foto](https://cloud.githubusercontent.com/assets/6184969/13398344/bc2c2e50-dedc-11e5-850d-0aa1fdb90fc6.png)
![video](https://cloud.githubusercontent.com/assets/6184969/13398345/bc4e7f5a-dedc-11e5-9b93-2c8ccfebb92d.png)

**Comment by LeandroBraier** [comment]
https://drive.google.com/file/d/0Bwr6Yvqae8IKZWdScmJaYmdBN0k/view

**Comment by FAAREIA** [comment]
Fijate ahora lea, cualquier cosa avisame

![foto](https://cloud.githubusercontent.com/assets/6184969/13399231/065212e8-dee1-11e5-9195-0ea530052187.png)
![video](https://cloud.githubusercontent.com/assets/6184969/13399232/0674cd1a-dee1-11e5-901d-6bd25b647a26.png)

Abrazo

**Comment by LeandroBraier** [comment]
Gracias Fede! Se te escaparon detalles.

1) Falta el nombre de la categoría arriba del video, que era "Mundo Viral" El Cinco que quede igual que en la sección de Nacimientos también, no hace falta lo que pusiste al pie tomado del video. Simplemente usá el fondo con nubes arriba y abajo del video.

2) Te faltó agrandar la fuente de Tránsito y convertirlo en 1 solo mensaje y no 3.

abrazo

**Comment by FAAREIA** [comment]
Hola Lea, la fuente del texto de Tránsito la agrandé (esta igual que las noticias) y entró bien los 3 mensajes. Si pongo solo 1 mensaje, igual no llega a entrar otra noticia.

Lo del video te lo mando
![video](https://cloud.githubusercontent.com/assets/6184969/13402408/e261d5a4-deee-11e5-852f-0ecc83e1de87.png)

**Comment by LeandroBraier** [comment]
Perfecto ahora Fede!

Entiendo lo que decís. LO mando a Eze y te si lo ve OK ya lo mandamos al
cliente.

Gracias!

abrazo

**Comment by LeandroBraier** [comment]
Te muestro como lo dejé al segundo, para que entiendas lo que te pedía.

![mock-up-videos](https://cloud.githubusercontent.com/assets/6719872/13402807/b4180810-def0-11e5-8128-98647f1f07f8.png)

abrazo

**Comment by FAAREIA** [comment]
Ahi va ^^, centrado

**Comment by LeandroBraier** [comment]
No me llegó nada eh.

**Comment by FAAREIA** [comment]
Hola Lea, no mandé nada simplemente te decia que al final era centrado y el video en dos partes. Solo eso ^^
Si necesitas algo de este tema avisame
Abrazo

**Comment by LeandroBraier** [comment]
Ah perfecto. Todo bien+ A Eze le encantó asi que mande al cliente.

**Comment by LeandroBraier** [comment]
@FAAREIA buena noticia! Aprobadísimo por el cliente. Solo me pidió agregar un detalle más que es muy simple, lo agrego yo. Me pasarías los PSD así lo aplicamos a MAgic Info?

Con eso ya quedaría hecho este pedido y podés tomar de base esta estructura para los otros templates que tenés que pensar para nuestro propio sistema de Digital Signage.

abrazo

**Comment by FAAREIA** [comment]
Buenísimo, ahi te pasé el archivo Photoshop por mail.

Abrazo

**Comment by LeandroBraier** [comment]
Gracias Fede! Por qué es un tiff? No es editable?

Yo necesito poder separar los elementos.

**Comment by FAAREIA** [comment]
Es editable, es lo mismo que un .psd pero ocupa menos porque tiene compresión zip ^^

**Comment by LeandroBraier** [comment]
Perfecto @FAAREIA gracias!!
